### ISSUE TITLE
AssertionError: can only join a started process

### ISSUE THREAD

**Issue by RonniSkansing** [Plazmaz/Sublist3r#10]
./sublist3r.py -v -b -p 80,443 -d hackerone.com

```
[-] Enumerating subdomains now for hackerone.com
[-] verbosity is enabled, will show the subdomains results in realtime
[-] Searching now in Baidu..
[-] Searching now in Google..
[-] Searching now in Virustotal..
[-] Searching now in GoogleTER..
[-] Searching now in Yahoo..
[-] Searching now in Netcraft..
[-] Searching now in SSL Certificates..
[-] Searching now in DnsDB..
[-] Searching now in Ask..
[-] Searching now in ThreatCrowd..
[-] Searching now in DNSdumpster..
[-] Searching now in Bing..
[-] Searching now in HackerTarget..
[-] Searching now in PassiveDNS..
Baidu: support.hackerone.com
Virustotal: a.ns.hackerone.com
Virustotal: b.ns.hackerone.com
Virustotal: api.hackerone.com
Virustotal: links.hackerone.com
Virustotal: support.hackerone.com
Virustotal: info.hackerone.com
Virustotal: www.hackerone.com
Yahoo: www.hackerone.com
Yahoo: support.hackerone.com
Netcraft: www.hackerone.com
SSL Certificates: support.hackerone.com
SSL Certificates: www.hackerone.com
SSL Certificates: links.hackerone.com
SSL Certificates: api.hackerone.com
SSL Certificates: go.hackerone.com
SSL Certificates: info.hackerone.com
ThreatCrowd: api.hackerone.com
ThreatCrowd: www.hackerone.com
DNSdumpster: support.hackerone.com
DNSdumpster: b.ns.hackerone.com
DNSdumpster: a.ns.hackerone.com
DNSdumpster: www.hackerone.com
Bing: support.hackerone.com
Traceback (most recent call last):
  File "./sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "./sublist3r.py", line 59, in main
    return scanner.scan()
  File "/root/sublister-se/Sublist3r/subscann3r.py", line 90, in scan
    enum.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 144, in jo
    assert self._popen is not None, 'can only join a started process'
```

**Comment by gwen001** [comment]
Same error for me.

**Comment by gwen001** [comment]
Fixed!

subscann3r.py, line 89:
```
for enum in enums:
     enum.start()
     enum.join()
```

Thanks to https://stackoverflow.com/questions/33667228/multiprocessing-can-only-join-a-started-process

**Comment by Plazmaz** [comment]
@gwen001 nice find! However I think this might negate multithreading entirely. I'll double check that and try to figure out what the underlying cause might be here.

**Comment by Plazmaz** [comment]
@gwen001 nice find! I'll throw that in to the codebase after I get a chance to test it. Thanks!
