### ISSUE TITLE
unbound method __init__() 

### ISSUE THREAD

**Issue by gopinath6** [Plazmaz/Sublist3r#11]
May i know what am  doing wrong?

C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r>c:\python27\python.exe -m pip install -r requirements.txt
Requirement already satisfied: argparse in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: dnspython in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests in c:\python27\lib\site-packages (from -r requirements.txt (line 3))

C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r>sublist3r.py -d glx.com

                     ____        _     _ _     _   _____
                    / ___| _   _| |__ | (_)___| |_|___ / _ __
                    \___ \| | | | '_ \| | / __| __| |_ \| '__|
                     ___) | |_| | |_) | | \__ \ |_ ___) | |
                    |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                    # Coded By Ahmed Aboul-Ela - @aboul3la
                    # Rewritten by Dylan Katz  - @Plazmaz

[-] Enumerating subdomains now for glx.com
[-] Searching now in Baidu..
Traceback (most recent call last):
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\sublist3r.py", line 59, in main
    return scanner.scan()
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\subscann3r.py", line 86, in scan
    enums = [enum(self.domain, [], q=subdomains_queue, silent=self.scan_flags.Silent, logger=self.logger) for enum in chosenEnums]
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\engines\engine.py", line 243, in __init__
    logger=logger)
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\engines\engine.py", line 32, in __init__
    multiprocessing.Process.__init__(self)
TypeError: unbound method __init__() must be called with Thread instance as first argument (got BaiduEnum instance instead)

C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r>python sublist3r.py -d glx.com

                     ____        _     _ _     _   _____
                    / ___| _   _| |__ | (_)___| |_|___ / _ __
                    \___ \| | | | '_ \| | / __| __| |_ \| '__|
                     ___) | |_| | |_) | | \__ \ |_ ___) | |
                    |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                    # Coded By Ahmed Aboul-Ela - @aboul3la
                    # Rewritten by Dylan Katz  - @Plazmaz

[-] Enumerating subdomains now for glx.com
[-] Searching now in Baidu..
Traceback (most recent call last):
  File "sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sublist3r.py", line 59, in main
    return scanner.scan()
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\subscann3r.py", line 86, in scan
    enums = [enum(self.domain, [], q=subdomains_queue, silent=self.scan_flags.Silent, logger=self.logger) for enum in chosenEnums]
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\engines\engine.py", line 243, in __init__
    logger=logger)
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r\engines\engine.py", line 32, in __init__
    multiprocessing.Process.__init__(self)
TypeError: unbound method __init__() must be called with Thread instance as first argument (got BaiduEnum instance instead)

**Comment by Plazmaz** [comment]
Hmm. Alright, I'll make sure to take a look when I get a chance! Thanks for the report!

**Comment by Plazmaz** [comment]
What OS and version of python are you running? Have you tried re-downloading the repo? I'm unable to reproduce this.

**Comment by zhugeburu** [comment]
Windows 10 64bit
Python 2.7.12
same error message.

**Comment by gopinath6** [comment]
My configs are
Win7 
Python 2.7.6. 

yes i tried  with new downloaded version also

[-] Enumerating subdomains now for example.com
[-] Searching now in Baidu..
Traceback (most recent call last):
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r-master\Sublist3r-master\sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r-master\Sublist3r-master\sublist3r.py", line 59, in main
    return scanner.scan()
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r-master\Sublist3r-master\subscann3r.py", line 86, in scan
    enums = [enum(self.domain, [], q=subdomains_queue, silent=self.scan_flags.Silent, logger=self.logger) for enum in chosenEnums]
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r-master\Sublist3r-master\engines\engine.py", line 243, in __init__
    logger=logger)
  File "C:\Users\kandasam\Dropbox\bug\Tools\Sublist3r-master\Sublist3r-master\engines\engine.py", line 32, in __init__
    multiprocessing.Process.__init__(self)
TypeError: unbound method __init__() must be called with Thread instance as first argument (got BaiduEnum instance instead)
