### ISSUE TITLE
Error when I run Sublist3r.py -d domain.com

### ISSUE THREAD

**Issue by hexben** [Plazmaz/Sublist3r#17]
Hello,

I have Win 7 with all updates. I also have Python 2.7 + 3.6. When I run sublist3r.py -d domain.com, I get the following error:

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\Sublist3r2\sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "C:\Users\xxx\Documents\Sublist3r2\sublist3r.py", line 59, in main
    return scanner.scan()
  File "C:\Users\xxx\Documents\Sublist3r2\subscann3r.py", line 88, in scan
    enum.start()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\multiproces
sing\process.py", line 99, in start
    assert self._popen is None, 'cannot start a process twice'
AttributeError: 'BaiduEnum' object has no attribute '_popen'

Your help is appreciated.
Thanks
Ben

**Comment by Plazmaz** [comment]
I think this should be resolved in the latest code.

**Comment by Plazmaz** [comment]
@hexben did that fix the issue for you?

**Comment by Plazmaz** [comment]
Going to close this issue, feel free to comment if it's still a problem.

**Comment by hexben** [comment]
No, the problem persists.
