### ISSUE TITLE
Error when running the -p option

### ISSUE THREAD

**Issue by jhaddix** [Plazmaz/Sublist3r#8]
hey again @Plazmaz , any ideas on this one?

``` python sublist3r.py -d TARGET.com -p 80 ```

```
[-] Starting port scan for the following ports: 80
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/tools/Sublist3r/sublister2/Sublist3r/util/port_scanner.py", line 27, in port_scan
    print("%s%s%s - %sFound open ports:%s %s%s%s" % (G, host, W, R, W, Y, ', '.join(openports), W))
NameError: global name 'G' is not defined

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/tools/Sublist3r/sublister2/Sublist3r/util/port_scanner.py", line 27, in port_scan
    print("%s%s%s - %sFound open ports:%s %s%s%s" % (G, host, W, R, W, Y, ', '.join(openports), W))
NameError: global name 'G' is not defined
```

**Comment by Plazmaz** [comment]
Able to reproduce, probably an easy fix, just accidentally screwed up my bash install so I'll fix that first 😋

**Comment by Plazmaz** [comment]
@jhaddix this should be fixed now. Please let me know if there's still issues :)

**Comment by jhaddix** [comment]
Working for ```-p``` now! TY!
