### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jhaddix** [Plazmaz/Sublist3r#9]
Getting the following on the Baidu Process:
```
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/tools/Sublist3r/engines/engine.py", line 39, in run
    domain_list = self.enumerate()
  File "/root/tools/Sublist3r/engines/enumarator_base.py", line 118, in enumerate
    links = self.extract_domains(resp)
  File "/root/tools/Sublist3r/engines/engine.py", line 270, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment
```

Any ideas?

**Comment by Plazmaz** [comment]
Will take a look as soon as I can!

**Comment by jhaddix** [comment]
Yep! No rush,  things still complete, just Baidu errors out =)

**Comment by jhaddix** [comment]
@Plazmaz are you on twitter? was gonna tweet out how awesome this fork is and wanted to reference you =)

**Comment by Plazmaz** [comment]
Yep, I'm @Plazmaz.

**Comment by Plazmaz** [comment]
Let me know if this is not as fixed as I think it is 😛

**Comment by jhaddix** [comment]
Another error now:
```
[-] Enumerating subdomains now for XXXXX
[-] Searching now in Baidu..
[-] Searching now in https://google.com/search?q={query}&btnG=Search&hl=en-US&biw=&bih=&gbv=1&start={page_no}&filter=0..
[-] Searching now in Virustotal..
[-] Searching now in GoogleTER..
[-] Searching now in Yahoo..
[-] Searching now in Netcraft..
[-] Searching now in SSL Certificates..
[-] Searching now in DnsDB..
[-] Searching now in Ask..
[-] Searching now in ThreatCrowd..
[-] Searching now in DNSdumpster..
[-] Searching now in Bing..
[-] Searching now in HackerTarget..
[-] Searching now in PassiveDNS..
Traceback (most recent call last):
  File "sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sublist3r.py", line 59, in main
    return scanner.scan()
  File "/root/tools/Sublist3r/subscann3r.py", line 88, in scan
    enum.enumerate()
  File "/root/tools/Sublist3r/engines/enumarator_base.py", line 113, in enumerate
    resp = self.send_req(query, page_no)
  File "/root/tools/Sublist3r/engines/enumarator_base.py", line 50, in send_req
    url = self.base_url.format(query=query, page_no=page_no)
AttributeError: 'GoogleEnum' object has no attribute 'format'
```

**Comment by jhaddix** [comment]
That last one does halt the execution.

**Comment by Plazmaz** [comment]
@jhaddix I can't reproduce this with 
`python sublist3r.py -v -d twitter.com`.
EDIT: Scratch that, found it.

**Comment by Plazmaz** [comment]
Fixed!

**Comment by jhaddix** [comment]
is there something wrong with my Python build? 
```
Traceback (most recent call last):
  File "sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sublist3r.py", line 59, in main
    return scanner.scan()
  File "/root/tools/Sublist3r/subscann3r.py", line 88, in scan
    enum.enumerate()
  File "/root/tools/Sublist3r/engines/enumarator_base.py", line 118, in enumerate
    links = self.extract_domains(resp)
  File "/root/tools/Sublist3r/engines/engine.py", line 270, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment
```

**Comment by jhaddix** [comment]
Don't know if this has anything to do with it but my target domain has a hyphen in it. Running on a non-hyphenated domain gives:

```
Traceback (most recent call last):
  File "sublist3r.py", line 78, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sublist3r.py", line 59, in main
    return scanner.scan()
  File "/root/tools/Sublist3r/subscann3r.py", line 90, in scan
    enum.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 144, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
```

**Comment by Plazmaz** [comment]
@jhaddix there's some weird versioning stuff that's been going on 😕
I'm off for the night, but I'll try to get to it as soon as I can.
